version: '3.8'

services:
  mysql:
    image: mysql:img
    volumes:
      - ./mysql-img/vol-mysql:/var/lib/mysql
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   timeout: 20s
    #   retries: 10
    deploy:
      # replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    ports:
      - 3306:3306

  soapapi:
    image: soap:ws
    volumes:
      - ./soap-server:/app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    ports:
      - 8888:8888
    environment:
      MYSQL_DB_HOST: mysql
      WEB_SERVICE_SOAP_HOST: soapapi

  rest:
    image: rest:ws
    volumes:
      - ./rest-server:/app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    ports:
      - 8080:8080
    environment:
      MYSQL_DB_HOST: mysql
      WEB_SERVICE_REST_HOST: restapi

  cliente:
    image: cliente:web
    volumes:
      - ./main-server:/app
    ports:
      - 3000:3000
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      APP_CLIENTE_HOST: cliente
      WEB_SERVICE_SOAP_HOST: soapapi


